config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contributions#index'
  resources :contributions do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :contribution
  belongs_to :user
  validates :text, presence: true, length: {minimum: 200 }
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  validates :text, presence: true, length: {minimum: 400 }
  def self.search(search)
    if search != ""
      Contribution.where('text LIKE(?)', "%#{search}%")
    else
      Contribution.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true 
  has_many :contributions
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def create
    comment = Comment.create(comment_params)
    redirect_to "/contributions/#{comment.contribution.id}"
  end


  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, contribution_id: params[:contribution_id])
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @contributions = Contribution.includes(:user).order("created_at DESC")
  end

  def new
    @contribution = Contribution.new
  end

  def create
    @contribution = Contribution.create(contribution_params)
    unless @contribution.save
      render "contributions/new"
    end
  end

  def destroy
    contribution = Contribution.find(params[:id])
    contribution.destroy
  end

  def edit
  end

  def update
    contribution = Contribution.find(params[:id])
    contribution.update(contribution_params)
  end

  def show
    @comment = Comment.new
    @comments = @contribution.comments.includes(:user)
  end

  def search
    @contributions = Contribution.search(params[:keyword])
  end

  private
  def contribution_params
    params.require(:contribution).permit(:title, :text).merge(user_id: current_user.id)
  end

  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @contributions = user.contributions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contributions/_contribution.html.erb
<div class="form">
  <div class="top-bar">
      <h2><%= contribution.title%></h2>
      <ul class = "more-list">
        <%= link_to(contribution_path(contribution.id), method: :get) do %>
          <button class="link">詳細</button>
        <% end %>
      <% if user_signed_in? && current_user.id == contribution.user_id %>
        <%= link_to(edit_contribution_path(contribution.id), method: :get) do %>
          <button class="link">編集</button>
        <% end %>
        <%= link_to(contribution_path(contribution.id), method: :delete) do %>
          <button class="link">削除</button>
        <% end %>
      <% end %>
      </ul>
  </div>
  <div class="main-bar">
    <div class="text">
      <%= contribution.text %>
    </div>
    <div class= "user">
      <span class ="contributer">投稿者</span>
      <a class = "name" href="/users/<%= contribution.user.id %>">
        <%= contribution.user.nickname %>
      </a>
    </div>
  </div>
</div>

app/views/contributions/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/contributions/_form.html.erb
  <div class = "new-form">
    <%= form_with model: @contribution, local: true do |form| %>
      <%= render 'contributions/error_messages', model: form.object %>
      <%= form.text_field :title, placeholder: "title",class: "title" %>
      <%= form.text_area :text, placeholder: "text",class: "text" %>
      <%= form.submit "投稿する",class: "submit" %>
    <% end %>
  </div>

app/views/contributions/create.html.erb
<div class="contents-row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/contributions/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/contributions/edit.html.erb
<div class="contents row">

  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { contribution: @contribution }%>
  </div>
  
</div>

app/views/contributions/index.html.erb
<%= render "shared/header" %>
  <div class='title-contents'>
    <h2 class='service-title'>
      あなたの意見を記事にしよう
    </h2>
    <p class='service-explain'>
      Letterは新聞をイメージした長文投稿アプリです
    </p>
    <p class='service-explain'>
      まずは１つ投稿してみよう
    </p>
  </div>
<div class="contents row">
  <% @contributions.each do |contribution| %>
    <%= render partial: "contribution", locals: { contribution: contribution }%>
  <% end %>
</div>

app/views/contributions/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>まずは投稿してみよう</h2>
    <%= render partial: "form", locals: { contribution: @contribution }%>
  </div>  
  
</div>

app/views/contributions/search.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <% @contributions.each do |contribution| %>
    <%= render partial: "contribution", locals: { contribution: contribution } %>
  <% end %>
</div>

app/views/contributions/show.html.erb
<%= render "shared/header" %>
<div class="form">
  <div class="top-bar">
    <h2><%= @contribution.title%></h2>
  <% if user_signed_in? && current_user.id == @contribution.user_id %>
  <ul class = "more-list">
      <% if user_signed_in? && current_user.id == @contribution.user_id %>
        <%= link_to(edit_contribution_path(@contribution.id), method: :get) do %>
          <button class="link">編集</button>
        <% end %>
        <%= link_to(contribution_path(@contribution.id), method: :delete) do %>
          <button class="link">削除</button>
        <% end %>
      <% end %>
  </ul>
  <% end %>
  </div>
  <div class="main-bar">
    <div class="text">
      <%= @contribution.text %>
    </div>
    <div class= "user">
      <span class ="contributer">投稿者</span>
      <a class = "name" href="/users/<%= @contribution.user.id %>">
        <%= @contribution.user.nickname %>
      </a>
    </div>
  </div>
</div>
</div>
<div class="container">
  <% if user_signed_in? %>
    <div class="new-form">
    <%= form_with(model: [@contribution, @comment], local: true) do |form| %>
        <%= render 'contributions/error_messages', model: form.object %>
        <h3>コメントは200字以上の入力が必要です</h3>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "text"%>
        <%= form.submit "投稿する",class: "submit" %>
    <% end %>
    </div>
  <% else %>
    <strong><p>コメントできません</p></strong>
  <% end %>
      <div class="comments">
      <h3>＜コメント一覧＞</h3>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>

app/views/contributions/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Letter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
      <p>
        Copyright Letter 2021.
      </p>
    </footer>
  </body>
</html>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("letter (4).png", class:"furima-icon"), "/" %>
    <div class="search-form">
      <%= form_with(url: search_contributions_path, local: true, method: :get, class: "search_container") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワードで検索", class: "input-box" %>
      <%= form.submit "検索", class: "search-btn" %>
      <% end %>
    </div>
  </div>
    <div class="nav">
      <ul class='lists-left'>
        <li><%= link_to 'ジャンル', "#", class: "category-list" %></li>
        <li><%= link_to '話題の記事', "#", class: "brand-list" %></li>
      </ul>
      <ul class='lists-right'>
        <% if user_signed_in? %>
            <li><%= link_to "マイページ", "/users/#{current_user.id}", class: "user-nickname" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %></li>
            <li><%= link_to "投稿する", new_contribution_path, class: "post" %></li>
        <% else %>
            <li><%= link_to "ログイン", new_user_session_path, class: "login" %></li>
            <li><%= link_to "新規登録", new_user_registration_path, class: "sign-up"%></li>
        <% end %>
      </ul>
    </div>
</header>

app/views/users/show.html.erb
<div class="contents row">
  <h3><%= @nickname %>さんの投稿一覧</h3>
  <% @contributions.each do |contribution| %>
    <%= render partial: "contributions/contribution", locals: { contribution: contribution }%>
  <% end %>
</div>